const S={chars:[],plan:null,project:null};const $=id=>document.getElementById(id);
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function words(){const n=$('story').value.trim().split(/\s+/).filter(Boolean).length;$('words').textContent=n+' word'+(n===1?'':'s')}
function renderChars(){const e=$('chars');if(!S.chars.length){e.innerHTML='<div class="empty">No characters yet. Add the people, animals or creatures in your story.</div>';return}e.innerHTML=S.chars.map((c,i)=>`<div class="char"><button class="del" onclick="removeChar(${i})">×</button><div class="avatar">${esc(c.name[0]||'?')}</div><strong>${esc(c.name)}</strong><span>${esc(c.appearance||'Appearance not specified')}</span><span>${esc(c.personality||'Personality not specified')}</span><span>🎙 ${esc(c.voice||'Auto voice')}</span></div>`).join('')}
function removeChar(i){S.chars.splice(i,1);renderChars()}
function project(){return{title:title(),story:$('story').value.trim(),characters:S.chars,settings:{style:$('style').value,format:$('format').value,duration:+$('duration').value,voiceMode:$('voice').value,subtitles:$('subs').checked,music:$('music').checked,sfx:$('sfx').checked,preserveScript:$('faithful').checked}}}
function title(){let x=$('story').value.trim().split(/[.!?]/)[0]||'Untitled AHM Story';return x.slice(0,55)}
function planDemo(p){const count=Math.max(10,Math.min(40,Math.round(p.settings.duration/6))),paras=p.story.split(/\n+/).map(x=>x.trim()).filter(Boolean),cs=p.characters.map(x=>x.name),sc=[];for(let i=0;i<count;i++){const a=Math.round(i*p.settings.duration/count),b=Math.round((i+1)*p.settings.duration/count),src=paras[i%Math.max(1,paras.length)]||p.story;sc.push({number:i+1,start:a,end:b,title:'Story Scene '+(i+1),characters:cs.slice(0,2).join(' + ')||'Main character(s)',action:'Follow the supplied story faithfully. '+src.slice(0,220),camera:i%3===0?'Wide cinematic establishing shot':i%3===1?'Medium character shot':'Emotional close-up',dialogue:'Dialogue will be produced from the story during the connected AI generation stage.'})}return{mode:'development',title:p.title,estimatedDuration:p.settings.duration,sceneCount:count,scenes:sc}}
function tm(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
async function makePlan(){const p=project();if(!p.story){toast('Write your story first.');return}S.project=p;$('generate').disabled=true;$('director').classList.remove('hidden');$('directorStatus').textContent='AHM Director is analyzing your story and building the scene plan…';$('scenes').innerHTML='';$('director').scrollIntoView({behavior:'smooth'});try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw 0;S.plan=await r.json()}catch(e){await new Promise(r=>setTimeout(r,700));S.plan=planDemo(p)}showPlan();$('generate').disabled=false}
function showPlan(){const p=S.plan;$('summary').textContent=p.sceneCount+' scenes • '+tm(p.estimatedDuration);$('directorStatus').innerHTML='<b>'+esc(p.title)+'</b><br>'+p.sceneCount+' scenes planned for '+tm(p.estimatedDuration)+'. Review before starting GPU generation.';$('scenes').innerHTML=p.scenes.map(s=>`<article class="scene"><div class="sceneTop"><b>SCENE ${String(s.number).padStart(2,'0')}</b><span class="time">${tm(s.start)} → ${tm(s.end)}</span></div><h3>${esc(s.title)}</h3><div><b>Characters:</b> ${esc(s.characters)}</div><div><b>Action:</b> ${esc(s.action)}</div><div><b>Camera:</b> ${esc(s.camera)}</div><div><b>Dialogue:</b> ${esc(s.dialogue)}</div></article>`).join('')}
async function render(){if(!S.plan)return;$('renderBox').classList.remove('hidden');$('render').disabled=true;$('regen').disabled=true;$('renderBox').scrollIntoView({behavior:'smooth'});$('log').innerHTML='';const stages=[['Preparing project',8],['Creating character consistency references',18],['Queueing video scenes',28],['Generating scene clips',55],['Preparing voices and dialogue',70],['Mixing music and sound effects',82],['Creating subtitles',90],['Stitching scenes with FFmpeg',97],['Finalizing MP4',100]];for(const [x,n] of stages){await new Promise(r=>setTimeout(r,650));$('stage').textContent=x;$('percent').textContent=n+'%';$('bar').style.width=n+'%';$('log').innerHTML+=`<div>› ${esc(x)} … done</div>`}$('result').classList.remove('hidden');$('previewTitle').textContent=S.project.title;$('result').scrollIntoView({behavior:'smooth'});$('render').disabled=false;$('regen').disabled=false}
function download(){const blob=new Blob([JSON.stringify({project:S.project,directorPlan:S.plan,note:'Development build. Connect RunPod/ComfyUI/Wan/FFmpeg worker for real MP4 generation.'},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AHM-Studio-production-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function reset(){S.chars=[];S.plan=null;S.project=null;$('story').value='';['director','renderBox','result'].forEach(x=>$(x).classList.add('hidden'));$('bar').style.width='0';$('percent').textContent='0%';renderChars();words();scrollTo({top:0,behavior:'smooth'})}
$('story').addEventListener('input',words);$('addBtn').onclick=()=>{$('modal').classList.remove('hidden');$('cName').focus()};$('close').onclick=()=>$('modal').classList.add('hidden');$('modal').querySelector('.backdrop').onclick=()=>$('modal').classList.add('hidden');$('save').onclick=()=>{const n=$('cName').value.trim();if(!n){toast('Enter a character name.');return}S.chars.push({name:n,appearance:$('cAppearance').value.trim(),personality:$('cPersonality').value.trim(),voice:$('cVoice').value.trim()});renderChars();$('modal').classList.add('hidden');toast(n+' added')};$('generate').onclick=makePlan;$('regen').onclick=makePlan;$('render').onclick=render;$('download').onclick=download;$('again').onclick=reset;$('newBtn').onclick=reset;$('advanced').onclick=()=>{$('advancedPanel').classList.toggle('hidden');$('advanced').lastElementChild.textContent=$('advancedPanel').classList.contains('hidden')?'＋':'−'};renderChars();words();